
/*
  _____  _      _   _                              
 |  __ \(_)    | | (_)                             
 | |  | |_  ___| |_ _  ___  _ __   __ _ _ __ _   _ 
 | |  | | |/ __| __| |/ _ \| '_ \ / _` | '__| | | |
 | |__| | | (__| |_| | (_) | | | | (_| | |  | |_| |
 |_____/|_|\___|\__|_|\___/|_| |_|\__,_|_|   \__, |
                                              __/ |
                                             |___/ 
*/
var jsonDict={"dico":[
	{"mot":"mail", "action":"goTo('https://webmail.utc.fr')"},
	{"mot":"@", "action":"goTo('https://webmail.utc.fr')"},
	{"mot":"webmail", "action":"goTo('https://webmail.utc.fr')"},
	{"mot":"email", "action":"goTo('https://webmail.utc.fr')"},
	{"mot":"shwet", "action":"goTo('http://shwet.fr/')"},
	{"mot":"ent", "action":"goTo('https://ent.utc.fr')"},
	{"mot":"bde", "action":"goTo('https://assos.utc.fr')"},
	{"mot":"asso", "action":"goTo('https://assos.utc.fr')"},
	{"mot":"assos", "action":"goTo('https://assos.utc.fr')"},
	{"mot":"interne", "action":"goTo('https://interne.utc.fr')"},
	{"mot":"inter", "action":"goTo('https://interne.utc.fr')"},
	{"mot":"troc", "action":"goTo('http://assos.utc.fr/trocutc/v2/')"},
	{"mot":"trocut", "action":"goTo('http://assos.utc.fr/trocutc/v2/')"},
	{"mot":"trocutc", "action":"goTo('http://assos.utc.fr/trocutc/v2/')"},
	{"mot":"payut", "action":"goTo('https://assos.utc.fr/payutc/')"},
	{"mot":"payutc", "action":"goTo('https://assos.utc.fr/payutc/')"},
	{"mot":"pay", "action":"goTo('https://assos.utc.fr/payutc/')"},
	{"mot":"polar", "action":"goTo('https://assos.utc.fr/polar/news/index')"},
	{"mot":"dossier", "action":"goTo('https://demeter.utc.fr/pls/portal30/ETUDIANTS.CONSULT_DODDIER_ETU_ETU_DYN.show')"},
	{"mot":"doss", "action":"goTo('https://demeter.utc.fr/pls/portal30/ETUDIANTS.CONSULT_DODDIER_ETU_ETU_DYN.show')"},
	{"mot":"emploi", "action":"emploiTemps", "nParam":1},
	{"mot":"temps", "action":"emploiTemps", "nParam":1},
	{"mot":"edt", "action":"emploiTemps", "nParam":1},
	{"mot":"emp", "action":"emploiTemps", "nParam":1},
	{"mot":"moodle", "action":"window.open('http://moodle.utc.fr')"},
	{"mot":"mood", "action":"window.open('http://moodle.utc.fr')"},
	{"mot":"filex", "action":"goTo('https://www.utc.fr/filex/')"},
	{"mot":"file", "action":"goTo('https://www.utc.fr/filex/')"},
	{"mot":"doc", "action":"goTo('http://utcenligne.utc.fr/mesdocuments/index.php')"},
	{"mot":"document", "action":"goTo('http://utcenligne.utc.fr/mesdocuments/index.php')"},
	{"mot":"documents", "action":"goTo('http://utcenligne.utc.fr/mesdocuments/index.php')"},
	{"mot":"tro", "action":"goTo('https://webapplis.utc.fr/Trombinoscope_web/')"},
	{"mot":"trombi", "action":"goTo('https://webapplis.utc.fr/Trombinoscope_web/')"},
	{"mot":"trombinoscope", "action":"goTo('https://webapplis.utc.fr/Trombinoscope_web/')"},
	{"mot":"cloud", "action":"window.open('https://cloud.utc.fr/')"},
	{"mot":"bibli", "action":"goTo('http://bibliotheque.utc.fr/medias/medias.aspx?INSTANCE=EXPLOITATION')"},
	{"mot":"bu", "action":"goTo('http://bibliotheque.utc.fr/medias/medias.aspx?INSTANCE=EXPLOITATION')"},
	{"mot":"wiki", "action":"searchWiki", "nParam":1},
	{"mot":"alcool", "action":"goTo('http://sweethome.mattgu.com/')"},
	{"mot":"conso", "action":"goTo('http://sweethome.mattgu.com/')"},
	{"mot":"short", "action":"callBitLy", "nParam":1},
	{"mot":"shorten", "action":"callBitLy", "nParam":1},
	{"mot":"raccourcir", "action":"callBitLy", "nParam":1},
	{"mot":"mailto", "action":"mailToFun", "nParam":1},
	{"mot":"rac", "action":"callBitLy", "nParam":1},
	{"mot":"bitly", "action":"callBitLy", "nParam":1},
	{"mot":"colinajo", "action":"goTo('http://nyan.cat')"},
	{"mot":"dogs", "action":"goTo('http://omfgdogs.com')"},
	{"mot":"google", "action":"searchGoogle", "nParam":1},
	{"mot":"g", "action":"searchGoogle", "nParam":1},
	{"mot":"facebook", "action":"searchFacebook", "nParam":1},
	{"mot":"fb", "action":"searchFacebook", "nParam":1},
	{"mot":"mycommand", "action":"goTo('http://www.troll.me/images/brick-tamland/you-think-youre-funny-but-youre-not.jpg')"},
	{"mot":"twitter", "action":"searchTwitter", "nParam":1},
	{"mot":"tw", "action":"searchTwitter", "nParam":1},
	{"mot":"pin", "action":"searchPinterest", "nParam":1},
	{"mot":"pinterest", "action":"searchPinterest", "nParam":1},
	{"mot":"map", "action":"searchMap", "nParam":1},
	{"mot":"maps", "action":"searchMap", "nParam":1},
	{"mot":"news", "action":"search_gNews", "nParam":1},
	{"mot":"gnews", "action":"search_gNews", "nParam":1},
	{"mot":"pic", "action":"goTo('http://assos.utc.fr/picasso')", "nParam":1},
	{"mot":"login", "action":"loginRetrieve", "nParam":2},
	{"mot":"boobs", "action":"goTo('http://gameofboobs.com/')"},
	{"mot":"wikipedia", "action":"searchWikipedia", "nParam":1},
	{"mot":"w", "action":"searchWikipedia", "nParam":1},
	{"mot":"help", "action":"goTo('pages/help.html')"},
	{"mot":"h", "action":"goTo('pages/help.html')"},
	{"mot":"?", "action":"goTo('pages/help.html')"},
	{"mot":"glucky", "action":"googleLucky", "nParam":1},
	{"mot":"gl", "action":"googleLucky", "nParam":1},
	{"mot":"gim", "action":"googleImage", "nParam":1},
	{"mot":"image", "action":"googleImage", "nParam":1},
	{"mot":"images", "action":"googleImage", "nParam":1},
	{"mot":"gi", "action":"googleImage", "nParam":1},
	{"mot":"git", "action":"window.open('http://github.com')"},
	{"mot":"github", "action":"window.open('http://github.com')"},
	{"mot":"yt", "action":"searchYoutube", "nParam":1},
	{"mot":"youtube", "action":"searchYoutube", "nParam":1},
	{"mot":"owner", "action":"alert('Owner: Jo Colina jo@jocolina.com')", "nParam":1},
	{"mot":"source", "action":"window.open('https://github.com/jsmrcaga/UTHub')"},
	{"mot":"dos", "action":"window.open('http://jamesfriend.com.au/pce-js/ibmpc-games/')"},
	{"mot":"mac", "action":"window.open('http://jamesfriend.com.au/pce-js/')"},
	{"mot":"got", "action":"window.open('http://stream-tv.me/watch-game-of-thrones-online-free/')"},
	{"mot":"match", "action":"matchReunion", "nParam":1},
	{"mot":"bieres", "action":"alert('Champion de service bieres au Pic: Axel Nicolas')"},
	{"mot":"wa", "action":"wolframAlphaSearch", "nParam":1},
	{"mot":"wolfram", "action":"wolframAlphaSearch", "nParam":1},
	{"mot":"wolframalpha", "action":"wolframAlphaSearch", "nParam":1},
	{"mot":"dropbox", "action":"window.open('http://dropbox.com')"},
	{"mot":"drop", "action":"window.open('http://dropbox.com')"},
	{"mot":"gdrive", "action":"window.open('http://drive.google.com')"},
	{"mot":"googleDrive", "action":"window.open('http://drive.google.com')"},
	{"mot":"drive", "action":"window.open('http://drive.google.com')"},
	{"mot":"commands", "action":"printCommands"},
	{"mot":"vacs", "action":"goTo('http://interne.utc.fr/direction-generale-des-services/decisions/article/calendrier-universitaire-fermeture')"},
	{"mot":"calendrier-utc", "action":"goTo('http://interne.utc.fr/direction-generale-des-services/decisions/article/calendrier-universitaire-fermeture')"},
	{"mot":"calutc", "action":"goTo('http://interne.utc.fr/direction-generale-des-services/decisions/article/calendrier-universitaire-fermeture')"},
	{"mot":"liens-dossier", "action":"goTo('https://demeter.utc.fr/portal/page?_pageid=9,376&_dad=portal30&_schema=PORTAL30')"},
	{"mot":"liens", "action":"goTo('https://demeter.utc.fr/portal/page?_pageid=9,376&_dad=portal30&_schema=PORTAL30')"},
	{"mot":"liens-utc", "action":"goTo('https://demeter.utc.fr/portal/page?_pageid=9,376&_dad=portal30&_schema=PORTAL30')"},
	{"mot":"liensutc", "action":"goTo('https://demeter.utc.fr/portal/page?_pageid=9,376&_dad=portal30&_schema=PORTAL30')"},
	{"mot":"dossier-etu", "action":"goTo('https://demeter.utc.fr/portal/page?_pageid=9,376&_dad=portal30&_schema=PORTAL30')"},
	{"mot":"dossieretu", "action":"goTo('https://demeter.utc.fr/portal/page?_pageid=9,376&_dad=portal30&_schema=PORTAL30')"},
	{"mot":"tx", "action":"goTo('https://demeter.utc.fr/pls/portal30/ENSEIGNEMENT.TX_INSCRIPTIONS_DYN.show')"},
	{"mot":"jury", "action":"goTo('https://demeter.utc.fr/pls/portal30/ETUDIANTS.CONSULT_DODDIER_ETU_ETU_DYN.show')"},
	{"mot":"jurys", "action":"goTo('https://demeter.utc.fr/pls/portal30/ETUDIANTS.CONSULT_DODDIER_ETU_ETU_DYN.show')"},
	{"mot":"uvs", "action":"goTo('https://demeter.utc.fr/pls/portal30/ENSEIGNEMENT.CONSULT_ENSEG_TAB_DYN.show?p_arg_names=p_aff&p_arg_values=TAB')"},
	{"mot":"uv", "action":"goTo('https://demeter.utc.fr/pls/portal30/ENSEIGNEMENT.CONSULT_ENSEG_TAB_DYN.show?p_arg_names=p_aff&p_arg_values=TAB')"},
	{"mot":"enseignements", "action":"goTo('https://demeter.utc.fr/pls/portal30/ENSEIGNEMENT.CONSULT_ENSEG_TAB_DYN.show?p_arg_names=p_aff&p_arg_values=TAB')"},
	{"mot":"3615", "action":"goTo('http://le3615utc.herokuapp.com/main/index#/')"},
	{"mot":"annuaire", "action":"goTo('http://le3615utc.herokuapp.com/main/index#/')"},
	{"mot":"reinscription", "action":"goTo('https://demeter.utc.fr/pls/portal30/ETUDIANTS.REINSC_ADMIN_LIGNE_11_DYN.show')"},
	{"mot":"inscription", "action":"goTo('http://wwwetu.utc.fr/rentree/')"},
	{"mot":"sublime", "action":"window.open('http://wwwetu.utc.fr/~colinajo/sublime/SublimeText2.zip')", "nParam":1},
	{"mot":"sublime-nix", "action":"window.open('http://wwwetu.utc.fr/~colinajo/sublime/SublimeText2nix.tar.bz2')", "nParam":1}
	]
	};
